################################################################################
#   Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved
#
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
################################################################################

# Datasource Configurations
wso2.datasources:
  dataSources:
    - name: APIM_ANALYTICS_DB
      description: "The datasource used for APIM statistics aggregated data."
      definition:
        type: RDBMS
        configuration:
          jdbcUrl: 'jdbc:h2:<PATH_TO_API-M_ANALYTICS_HOME>/wso2/worker/database/APIM_ANALYTICS_DB;AUTO_SERVER=TRUE'
          username: wso2carbon
          password: wso2carbon
          driverClassName: org.h2.Driver
          maxPoolSize: 50
          idleTimeout: 60000
          connectionTestQuery: SELECT 1
          validationTimeout: 30000
          isAutoCommit: false

wso2.securevault:
  secretRepository:
    type: org.wso2.carbon.secvault.repository.DefaultSecretRepository
    parameters:
      privateKeyAlias: wso2carbon
      keystoreLocation: <PATH_TO_API-M_ANALYTICS_HOME>/resources/security/securevault.jks
      secretPropertiesFile: <PATH_TO_API-M_ANALYTICS_HOME>/conf/worker/secrets.properties
  masterKeyReader:
    type: org.wso2.carbon.secvault.reader.DefaultMasterKeyReader
    parameters:
      masterKeyReaderFile: <PATH_TO_API-M_ANALYTICS_HOME>/conf/worker/master-keys.yaml

# GDPR Client Configuration Parameters
wso2.gdpr:
  # databases which includes the username entries in its tables
  databases:
    - databaseName: APIM_ANALYTICS_DB
      tableEntries:
        - tableName: ApiCreatorAlertConfiguration
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiExeTime_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiExeTime_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiExeTime_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiExeTime_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiExeTime_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiExeTime_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiFaultyInvocationAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiFaultyInvocationAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiFaultyInvocationAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiFaultyInvocationAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiFaultyInvocationAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiFaultyInvocationAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiLastAccessSummary
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiLastAccessSummary
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApimAbnormalBackendTimeAlert
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimAbnormalReqAlert
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimAbnormalResponseTimeAlert
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimAlertStakeholderInfo
          columnName: USERID
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimAlertStakeholderInfo
          columnName: EMAILS
          columnType: EMAIL
          isTextReplace: true
          preReplaceText: ","
          postReplaceText: ","
        - tableName: ApimAllAlert
          columnName: MESSAGE
          isSuperTenantUsernameHasTenantDomain: true
          isTextReplace: true
          preReplaceText: "owned by "
          postReplaceText: " for api"
        - tableName: ApimAllAlert
          columnName: MESSAGE
          isSuperTenantUsernameHasTenantDomain: true
          columnType: IP
          isTextReplace: true
          preReplaceText: "IP ("
          postReplaceText: ") detected by user:{{CURRENT_IP_USERNAME_VALUE}} using"
        - tableName: ApimAllAlert
          columnName: MESSAGE
          isSuperTenantUsernameHasTenantDomain: true
          isTextReplace: true
          preReplaceText: "owned by "
          postReplaceText: "."
        - tableName: ApimAllAlert
          columnName: MESSAGE
          isSuperTenantUsernameHasTenantDomain: true
          isTextReplace: true
          preReplaceText: "User "
          postReplaceText: " frequently"
        - tableName: ApimAllAlert
          columnName: MESSAGE
          isSuperTenantUsernameHasTenantDomain: true
          isTextReplace: true
          preReplaceText: "detected by user :"
          postReplaceText: " using application"
        - tableName: ApimApiAvailabilityInfo
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimApiHealthMonitorAlert
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimIPAccessAbnormalityAlert
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimIPAccessAbnormalityAlert
          columnName: IP
          columnType: IP
          ipUsernameColumnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimIPAccessAlertCount
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimIPAccessSummary
          columnName: IP
          columnType: IP
          ipUsernameColumnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimRequestPatternChangedAlert
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimTierLimitHittingAlert
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimTierLimitHittingAlert
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimTierLimitHittingAlert
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApimTierLimitHittingAlert
          columnName: MESSAGE
          isSuperTenantUsernameHasTenantDomain: true
          isTextReplace: true
          preReplaceText: "User "
          postReplaceText: " frequently"
        - tableName: APIM_ReqCountAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: APIM_ReqCountAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: APIM_ReqCountAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: APIM_ReqCountAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: APIM_ReqCountAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: APIM_ReqCountAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiPerDestinationAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiPerDestinationAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiPerDestinationAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiPerDestinationAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiPerDestinationAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiPerDestinationAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiResPathPerApp_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiResPathPerApp_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiResPathPerApp_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiResPathPerApp_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiResPathPerApp_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiResPathPerApp_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiSubAlertConf
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_DAYS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiThrottledOutAgg_DAYS
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_HOURS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiThrottledOutAgg_HOURS
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_MINUTES
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiThrottledOutAgg_MINUTES
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_MONTHS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiThrottledOutAgg_MONTHS
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_SECONDS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiThrottledOutAgg_SECONDS
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiThrottledOutAgg_YEARS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiThrottledOutAgg_YEARS
          columnName: SUBSCRIBER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserBrowserAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserBrowserAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserBrowserAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserBrowserAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserBrowserAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserBrowserAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_DAYS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiUserPerAppAgg_DAYS
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_HOURS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiUserPerAppAgg_HOURS
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_MINUTES
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiUserPerAppAgg_MINUTES
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_MONTHS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiUserPerAppAgg_MONTHS
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_SECONDS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiUserPerAppAgg_SECONDS
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiUserPerAppAgg_YEARS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: ApiUserPerAppAgg_YEARS
          columnName: APPLICATIONOWNER
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiVersionPerAppAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiVersionPerAppAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiVersionPerAppAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiVersionPerAppAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiVersionPerAppAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: ApiVersionPerAppAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: GeoLocationAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: GeoLocationAgg_DAYS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: GeoLocationAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: GeoLocationAgg_HOURS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: GeoLocationAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: GeoLocationAgg_MINUTES
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: GeoLocationAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: GeoLocationAgg_MONTHS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: GeoLocationAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: GeoLocationAgg_SECONDS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: GeoLocationAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: GeoLocationAgg_YEARS
          columnName: USERNAME
          isSuperTenantUsernameHasTenantDomain: true
        - tableName: MonetizationAgg_DAYS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: MonetizationAgg_HOURS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: MonetizationAgg_MINUTES
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: MonetizationAgg_MONTHS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: MonetizationAgg_SECONDS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
        - tableName: MonetizationAgg_YEARS
          columnName: APICREATOR
          isSuperTenantUsernameHasTenantDomain: false
